CREATE TABLE "hyperparameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hyperparameter_set_name" varchar(100),
  "n_estimators" int,
  "max_depth" int,
  "min_samples_split" int,
  "subsample" float,
  "learning_rate" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "optimizer" varchar(50),
  "batch_size" int,
  "epochs" int,
  "random_state" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" varchar(100) UNIQUE NOT NULL,
  "model_architecture" varchar(100),
  "target" varchar(15),
  "environment_state" "enum(Development,Learning,Demo,Production,Relearning)",
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "dataset_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_name" varchar(100) UNIQUE NOT NULL,
  "start_date" date,
  "end_date" date,
  "row_count" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "dataset_version_filter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filter" varchar(50) NOT NULL,
  "operator" varchar(10) NOT NULL,
  "filter_value" varchar(255) NOT NULL,
  "description" varchar(255),
  "dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version" varchar(100),
  "ml_model_id" int,
  "hyperparameter_id" int,
  "dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version_feature" (
  "ml_model_version_id" int,
  "feature_id" int,
  "primary" key(ml_model_version_id,feature_id)
);

CREATE TABLE "feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar(100) NOT NULL,
  "feature_description" text,
  "source_data" varchar(100) NOT NULL,
  "time_lag_steps" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "feature_parameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parameter_name" varchar(100) NOT NULL,
  "parameter_value" varchar(100) NOT NULL,
  "feature_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "test_statistical_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_statistical_metrics_name" varchar(100) NOT NULL,
  "test_statistical_value" float NOT NULL,
  "ml_model_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "live_trading_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "live_trading_metrics_name" varchar(100) NOT NULL,
  "live_trading_value" float NOT NULL,
  "ml_model_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_signal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ml_model_version_id" int NOT NULL,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "signal_type" "enum(BUY_LONG,SELL_SHORT,EXIT_LONG,EXIT_SHORT)" NOT NULL,
  "order_type" "enum(MARKET,LIMIT,STOP,STOP_LIMIT)" NOT NULL,
  "ml_suggested_entry_price" float NOT NULL,
  "ml_suggested_stop_loss" float,
  "ml_suggested_take_profit" float,
  "position_size" float NOT NULL,
  "signal_time" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "hyperparameter"."n_estimators" IS 'A döntési fák száma a modellben';

COMMENT ON COLUMN "hyperparameter"."max_depth" IS 'A fák maximális mélysége';

COMMENT ON COLUMN "hyperparameter"."min_samples_split" IS 'A csomópont felosztásához szükséges mintaszám';

COMMENT ON COLUMN "hyperparameter"."subsample" IS 'Sorok mintavételezési aránya (0.0 - 1.0)';

COMMENT ON COLUMN "hyperparameter"."learning_rate" IS 'Tanulási ráta / lépésköz (pl. 0.01, 0.1)';

COMMENT ON COLUMN "hyperparameter"."colsample_bytree" IS 'Oszlopok (feature-ök) mintavételezési aránya fánként (0.0 - 1.0)';

COMMENT ON COLUMN "hyperparameter"."reg_alpha" IS 'L1 regularizáció (XGBoost Alpha)';

COMMENT ON COLUMN "hyperparameter"."reg_lambda" IS 'L2 regularizáció (XGBoost Lambda)';

COMMENT ON COLUMN "hyperparameter"."optimizer" IS 'Optimalizáló algoritmus neve (pl. adam, sgd)';

COMMENT ON COLUMN "hyperparameter"."batch_size" IS 'Kötegméret a tanítás során';

COMMENT ON COLUMN "hyperparameter"."epochs" IS 'Tanítási iterációk száma';

COMMENT ON COLUMN "hyperparameter"."random_state" IS 'A reprodukálhatóságért felelős seed szám(Mindig ugyan annak a számnak kell lennie )';

COMMENT ON COLUMN "ml_model"."model_architecture" IS 'Modell típusa/algoritmusa (pl. XGBoost)';

COMMENT ON COLUMN "ml_model"."target" IS 'A célváltozó, amit a modell jósol - long/short';

COMMENT ON COLUMN "ml_model"."environment_state" IS 'A modell aktuális életciklus-állapota (pl. Production, Testing)';

COMMENT ON COLUMN "dataset_version"."version_name" IS 'Pl. v1.0-2026-07, v2.1-with-RSI';

COMMENT ON COLUMN "dataset_version"."start_date" IS 'Az adatbázisban szereplő legelső tőzsdei nap';

COMMENT ON COLUMN "dataset_version"."end_date" IS 'Az adatbázisban szereplő legutolsó tőzsdei nap';

COMMENT ON COLUMN "dataset_version"."row_count" IS 'Hány sorból áll a dataset (kontrollhoz)';

COMMENT ON COLUMN "dataset_version_filter"."filter" IS 'pl. volume, close_price, asset_type';

COMMENT ON COLUMN "dataset_version_filter"."operator" IS 'pl. >, <, =, IN, BETWEEN';

COMMENT ON COLUMN "dataset_version_filter"."filter_value" IS 'pl. 100000, US, 2026-01-01';

COMMENT ON COLUMN "ml_model_version"."model_version" IS 'Modell verziószáma (pl. v2.4.1)';

COMMENT ON COLUMN "feature"."source_data" IS 'Honnan származik pl. OHLCV, OrderBook, Sentiment';

COMMENT ON COLUMN "feature"."time_lag_steps" IS 'Hány lépéssel van eltolva (pl. 1 órával ez elött)';

COMMENT ON COLUMN "feature_parameter"."parameter_value" IS 'Az indikátor értékei';

COMMENT ON COLUMN "test_statistical_metric"."test_statistical_value" IS 'Az tesztelésből/learning származtatott statisztikai értékek';

COMMENT ON COLUMN "live_trading_metric"."live_trading_value" IS 'Az éleskereskedésből származtatott statisztikai értékek';

COMMENT ON COLUMN "ml_signal"."ticker" IS 'pl. NQ, BTCUSDT';

COMMENT ON COLUMN "ml_signal"."ml_suggested_entry_price" IS 'Az ML által javasolt beszálló ár';

COMMENT ON COLUMN "ml_signal"."ml_suggested_stop_loss" IS 'Az ML által kalkulált kezdeti Stop Loss';

COMMENT ON COLUMN "ml_signal"."ml_suggested_take_profit" IS 'Az ML által kalkulált kezdeti Take Profit';

COMMENT ON COLUMN "ml_signal"."position_size" IS 'Az ML által javasolt méret (tőke % vagy darab)';

COMMENT ON COLUMN "ml_signal"."signal_time" IS 'A jel keletkezésének pillanata';

ALTER TABLE "dataset_version_filter" ADD FOREIGN KEY ("dataset_version_id") REFERENCES "dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("ml_model_id") REFERENCES "ml_model" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("hyperparameter_id") REFERENCES "hyperparameter" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("dataset_version_id") REFERENCES "dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version_feature" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version_feature" ADD FOREIGN KEY ("feature_id") REFERENCES "feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feature_parameter" ADD FOREIGN KEY ("feature_id") REFERENCES "feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "test_statistical_metric" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "live_trading_metric" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;
