CREATE TABLE "ML_Model" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" varchar(100) UNIQUE NOT NULL,
  "model_architecture" varchar(100),
  "target" varchar(15),
  "environment_state" "enum(Development,Learing,Demo,Production,Relearning)",
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "hyperparameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hyperparameter_set_name" varchar(100) UNIQUE NOT NULL,
  "n_estimators" int,
  "max_depth" int,
  "min_samples_split" int,
  "subsample" float,
  "learning_rate" float,
  "optimizer" varchar(50),
  "batch_size" int,
  "epochs" int,
  "regularization_penalty" float,
  "ML_Model_id" int,
  "random_state" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "dataset_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_name" varchar(100) UNIQUE NOT NULL,
  "start_date" date,
  "end_date" date,
  "row_count" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "dataset_version_filter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filter" varchar(50) NOT NULL,
  "operator" varchar(10) NOT NULL,
  "filter_value" varchar(255) NOT NULL,
  "description" varchar(255),
  "dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_versions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version" varchar(100),
  "ML_Model_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version_features" (
  "ml_model_version_id" int,
  "feature_id" int,
  "primary" key(ml_model_version_id,feature_id)
);

CREATE TABLE "features" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar(100) NOT NULL,
  "feature_description" text,
  "source_data" varchar(100) NOT NULL,
  "time_lag_steps" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "feature_parameters" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parameter_name" varchar(100) NOT NULL,
  "parameter_value" varchar(100) NOT NULL,
  "feature_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "test_statistical_metrics" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_statistical_metrics_name" varchar(100) NOT NULL,
  "test_statistical_value" float NOT NULL,
  "ml_model_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "Live_trading_metrics" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Live_trading_metrics_name" varchar(100) NOT NULL,
  "Live_trading_value" float NOT NULL,
  "ml_model_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

COMMENT ON COLUMN "ML_Model"."model_architecture" IS 'Modell típusa/algoritmusa (pl. XGBoost)';

COMMENT ON COLUMN "ML_Model"."target" IS 'A célváltozó, amit a modell jósol - long/short';

COMMENT ON COLUMN "ML_Model"."environment_state" IS 'A modell aktuális életciklus-állapota (pl. Production, Testing)';

COMMENT ON COLUMN "hyperparameter"."n_estimators" IS 'A döntési fák száma a modellben';

COMMENT ON COLUMN "hyperparameter"."max_depth" IS 'A fák maximális mélysége';

COMMENT ON COLUMN "hyperparameter"."min_samples_split" IS 'A csomópont felosztásához szükséges minimális mintaszám';

COMMENT ON COLUMN "hyperparameter"."subsample" IS 'Az adatok hány százalékát használja egy fához (0.0 - 1.0)';

COMMENT ON COLUMN "hyperparameter"."learning_rate" IS 'Tanulási ráta / lépésköz (pl. 0.01, 0.1)';

COMMENT ON COLUMN "hyperparameter"."optimizer" IS 'Optimalizáló algoritmus neve (pl. adam, sgd)';

COMMENT ON COLUMN "hyperparameter"."batch_size" IS 'Kötegméret a tanítás során';

COMMENT ON COLUMN "hyperparameter"."epochs" IS 'Tanítási iterációk száma';

COMMENT ON COLUMN "hyperparameter"."regularization_penalty" IS 'L1/L2 regulázás mértéke (Alpha/Lambda)';

COMMENT ON COLUMN "hyperparameter"."random_state" IS 'A reprodukálhatóságért felelős seed szám(Mindig ugyan annak a számnak kell lennie )';

COMMENT ON COLUMN "dataset_version"."version_name" IS 'Pl. v1.0-2026-07, v2.1-with-RSI';

COMMENT ON COLUMN "dataset_version"."start_date" IS 'Az adatbázisban szereplő legelső tőzsdei nap';

COMMENT ON COLUMN "dataset_version"."end_date" IS 'Az adatbázisban szereplő legutolsó tőzsdei nap';

COMMENT ON COLUMN "dataset_version"."row_count" IS 'Hány sorból áll a dataset (kontrollhoz)';

COMMENT ON COLUMN "dataset_version_filter"."filter" IS 'pl. volume, close_price, asset_type';

COMMENT ON COLUMN "dataset_version_filter"."operator" IS 'pl. >, <, =, IN, BETWEEN';

COMMENT ON COLUMN "dataset_version_filter"."filter_value" IS 'pl. 100000, US, 2026-01-01';

COMMENT ON COLUMN "ml_model_versions"."model_version" IS 'Modell verziószáma (pl. v2.4.1)';

COMMENT ON COLUMN "features"."source_data" IS 'Honnan származik pl. OHLCV, OrderBook, Sentiment';

COMMENT ON COLUMN "features"."time_lag_steps" IS 'Hány lépéssel van eltolva (pl. 1 órával ez elött)';

COMMENT ON COLUMN "feature_parameters"."parameter_value" IS 'Az indikátor értékei';

COMMENT ON COLUMN "test_statistical_metrics"."test_statistical_value" IS 'Az indikátor értékei';

COMMENT ON COLUMN "Live_trading_metrics"."Live_trading_value" IS 'Az indikátor értékei';
