      ------ Timeseries Data ------
CREATE TABLE "timeseries_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "time" timestamp NOT NULL,
  "open" float NOT NULL,
  "high" float NOT NULL,
  "low" float NOT NULL,
  "close" float NOT NULL,
  "log_return" float NOT NULL,
  "dataset_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

      ------ ML Model ------
CREATE TABLE "hyperparameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hyperparameter_set_name" varchar(100),
  "n_estimators" int,
  "max_depth" int,
  "min_samples_split" int,
  "subsample" float,
  "learning_rate" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "optimizer" varchar(50),
  "batch_size" int,
  "epochs" int,
  "random_state" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" varchar(100) UNIQUE NOT NULL,
  "model_architecture" varchar(100),
  "target" varchar(15),
  "environment_state" "enum(Development,Learning,Demo,Production,Relearning)",
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version" varchar(100),
  "ml_model_id" int,
  "hyperparameter_id" int,
  "dataset_version_id" int,
  "optimization_variant_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version_feature" (
  "ml_model_version_id" int,
  "feature_id" int,
  "primary" key(ml_model_version_id,feature_id)
);

CREATE TABLE "feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar(100) NOT NULL,
  "feature_description" text,
  "source_data" varchar(100) NOT NULL,
  "time_lag_steps" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "feature_parameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parameter_name" varchar(100) NOT NULL,
  "parameter_value" varchar(100) NOT NULL,
  "feature_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "timeseries_feature_value" (
  "timeseries_data_id" bigint NOT NULL,
  "feature_id" int NOT NULL,
  "feature_value" float NOT NULL,
  "primary" key(timeseries_data_id,feature_id)
);

CREATE TABLE "dataset_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_name" varchar(100) UNIQUE NOT NULL,
  "start_date" date,
  "end_date" date,
  "candel_count" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "dataset_version_filter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filter" varchar(50) NOT NULL,
  "operator" varchar(10) NOT NULL,
  "filter_value" varchar(255) NOT NULL,
  "description" varchar(255),
  "dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "optimization_variant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "max_depth" int,
  "learning_rate" float,
  "n_estimators" int,
  "subsample" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "wfe_50plus_db" int,
  "atlag_wfe_pct" float,
  "atlag_sharpe" float,
  "max_sharpe" float,
  "is_best_for_version" bool DEFAULT false,
  "ml_model_id" int NOT NULL,
  "dataset_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "optimization_trade" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "entry_time" timestamp NOT NULL,
  "entry_price" float NOT NULL,
  "exit_time" timestamp NOT NULL,
  "exit_price" float NOT NULL,
  "pnl_raw" float NOT NULL,
  "pnl_log_return" float NOT NULL,
  "optimization_variant_id" int NOT NULL,
  "wfo_fold_index" int NOT NULL DEFAULT 1,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "test_statistical_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_statistical_metrics_name" varchar(100) NOT NULL,
  "test_statistical_value" float NOT NULL,
  "optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "live_trading_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "live_trading_metrics_name" varchar(100) NOT NULL,
  "live_trading_value" float NOT NULL,
  "optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "ml_signal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "signal_type" "enum(BUY_LONG,SELL_SHORT,EXIT_LONG,EXIT_SHORT)" NOT NULL,
  "confidence" float NOT NULL,
  "ml_suggested_entry_price" float NOT NULL,
  "ml_suggested_stop_loss" float,
  "ml_suggested_take_profit" float,
  "position_size" float NOT NULL,
  "signal_time" timestamp DEFAULT (now()),
  "ml_model_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "timeseries_data"."time" IS 'The time of the candle (e.g. 2018-01-02T00:00:00+01:00)';

COMMENT ON COLUMN "timeseries_data"."log_return" IS 'e.g.: 0.01 = +1%';

COMMENT ON COLUMN "hyperparameter"."n_estimators" IS 'The number of decision trees in the model';

COMMENT ON COLUMN "hyperparameter"."max_depth" IS 'The maximum depth of the trees';

COMMENT ON COLUMN "hyperparameter"."min_samples_split" IS 'The minimum number of samples required to split an internal node';

COMMENT ON COLUMN "hyperparameter"."subsample" IS 'Subsample ratio of the training instances (0.0 - 1.0)';

COMMENT ON COLUMN "hyperparameter"."learning_rate" IS 'Learning rate / step size (e.g. 0.01, 0.1)';

COMMENT ON COLUMN "hyperparameter"."colsample_bytree" IS 'Subsample ratio of columns when constructing each tree (0.0 - 1.0)';

COMMENT ON COLUMN "hyperparameter"."reg_alpha" IS 'L1 regularization term on weights (XGBoost Alpha)';

COMMENT ON COLUMN "hyperparameter"."reg_lambda" IS 'L2 regularization term on weights (XGBoost Lambda)';

COMMENT ON COLUMN "hyperparameter"."optimizer" IS 'Name of the optimizer algorithm (e.g. adam, sgd)';

COMMENT ON COLUMN "hyperparameter"."batch_size" IS 'Batch size during training';

COMMENT ON COLUMN "hyperparameter"."epochs" IS 'Number of training iterations';

COMMENT ON COLUMN "hyperparameter"."random_state" IS 'Seed number responsible for reproducibility (Must always be the same number)';

COMMENT ON COLUMN "ml_model"."model_architecture" IS 'Model type/algorithm (e.g. XGBoost)';

COMMENT ON COLUMN "ml_model"."target" IS 'The target variable that the model predicts - long/short';

COMMENT ON COLUMN "ml_model"."environment_state" IS 'The current lifecycle state of the model (e.g. Production, Testing)';

COMMENT ON COLUMN "ml_model_version"."model_version" IS 'Model version number (e.g. v2.4.1)';

COMMENT ON COLUMN "feature"."source_data" IS 'Where it originates from e.g. OHLCV, OrderBook, Sentiment';

COMMENT ON COLUMN "feature"."time_lag_steps" IS 'How many steps it is shifted by (e.g. 1 hour before this)';

COMMENT ON COLUMN "feature_parameter"."parameter_value" IS 'The values of the indicator';

COMMENT ON COLUMN "timeseries_feature_value"."feature_value" IS 'The actual calculated numerical value in the given hour';

COMMENT ON COLUMN "dataset_version"."version_name" IS 'E.g. v1.0-2026-07, v2.1-with-RSI';

COMMENT ON COLUMN "dataset_version"."start_date" IS 'The very first exchange day in the database';

COMMENT ON COLUMN "dataset_version"."end_date" IS 'The very last exchange day in the database';

COMMENT ON COLUMN "dataset_version_filter"."filter" IS 'e.g. volume, close_price, asset_type';

COMMENT ON COLUMN "dataset_version_filter"."operator" IS 'e.g. >, <, =, IN, BETWEEN';

COMMENT ON COLUMN "dataset_version_filter"."filter_value" IS 'e.g. 100000, US, 2026-01-01';

COMMENT ON COLUMN "optimization_variant"."wfe_50plus_db" IS 'WFE_50plus_db';

COMMENT ON COLUMN "optimization_variant"."atlag_wfe_pct" IS 'Average_WFE_%';

COMMENT ON COLUMN "optimization_variant"."atlag_sharpe" IS 'Average_Sharpe';

COMMENT ON COLUMN "optimization_variant"."max_sharpe" IS 'Max_Sharpe';

COMMENT ON COLUMN "optimization_variant"."is_best_for_version" IS 'false = not the best, true = best optimazation for the version';

COMMENT ON COLUMN "optimization_trade"."entry_time" IS 'The execution time when the position was opened';

COMMENT ON COLUMN "optimization_trade"."entry_price" IS 'The execution entry price';

COMMENT ON COLUMN "optimization_trade"."exit_time" IS 'The execution time when the position was closed';

COMMENT ON COLUMN "optimization_trade"."exit_price" IS 'The execution exit price';

COMMENT ON COLUMN "optimization_trade"."pnl_raw" IS 'Net profit or loss in points or absolute currency value';

COMMENT ON COLUMN "optimization_trade"."pnl_log_return" IS 'The return of the trade formatted as log return';

COMMENT ON COLUMN "ml_signal"."ticker" IS 'e.g. NQ, BTCUSDT';

COMMENT ON COLUMN "ml_signal"."confidence" IS 'probability of long/short';

COMMENT ON COLUMN "ml_signal"."ml_suggested_entry_price" IS 'The entry price suggested by the ML';

COMMENT ON COLUMN "ml_signal"."ml_suggested_stop_loss" IS 'The initial Stop Loss calculated by the ML';

COMMENT ON COLUMN "ml_signal"."ml_suggested_take_profit" IS 'The initial Take Profit calculated by the ML';

COMMENT ON COLUMN "ml_signal"."position_size" IS 'The size suggested by the ML (capital % or pieces)';

COMMENT ON COLUMN "ml_signal"."signal_time" IS 'The moment the signal was generated';

ALTER TABLE "timeseries_data" ADD FOREIGN KEY ("dataset_version_id") REFERENCES "dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "timeseries_feature_value" ADD FOREIGN KEY ("timeseries_data_id") REFERENCES "timeseries_data" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "timeseries_feature_value" ADD FOREIGN KEY ("feature_id") REFERENCES "feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "dataset_version_filter" ADD FOREIGN KEY ("dataset_version_id") REFERENCES "dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("ml_model_id") REFERENCES "ml_model" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("hyperparameter_id") REFERENCES "hyperparameter" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("dataset_version_id") REFERENCES "dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version_feature" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version_feature" ADD FOREIGN KEY ("feature_id") REFERENCES "feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_signal" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feature_parameter" ADD FOREIGN KEY ("feature_id") REFERENCES "feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "test_statistical_metric" ADD FOREIGN KEY ("optimization_variant_id") REFERENCES "optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "live_trading_metric" ADD FOREIGN KEY ("optimization_variant_id") REFERENCES "optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "optimization_trade" ADD FOREIGN KEY ("optimization_variant_id") REFERENCES "optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("optimization_variant_id") REFERENCES "optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "optimization_variant" ADD FOREIGN KEY ("ml_model_id") REFERENCES "ml_model" ("id") DEFERRABLE INITIALLY IMMEDIATE;

      ------ Personal analysis strategy ------