CREATE TABLE "timeseries_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "time" timestamp NOT NULL,
  "open" float NOT NULL,
  "high" float NOT NULL,
  "low" float NOT NULL,
  "close" float NOT NULL,
  "log_return" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_hyperparameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hyperparameter_set_name" varchar(100),
  "n_estimators" int,
  "max_depth" int,
  "min_samples_split" int,
  "subsample" float,
  "learning_rate" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "optimizer" varchar(50),
  "batch_size" int,
  "epochs" int,
  "random_state" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" varchar(100) UNIQUE NOT NULL,
  "model_architecture" varchar(100),
  "target" varchar(15),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version" varchar(100),
  "environment_state" "enum(Development,Learning,Demo,Production,Relearning)",
  "ml_model_id" int,
  "ml_hyperparameter_id" int,
  "ml_dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version_feature" (
  "ml_model_version_id" int,
  "ml_feature_id" int,
  "primary" key(ml_model_version_id,ml_feature_id)
);

CREATE TABLE "ml_feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar(100) NOT NULL,
  "feature_description" text,
  "source_data" varchar(100) NOT NULL,
  "time_lag_steps" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_feature_parameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parameter_name" varchar(100) NOT NULL,
  "parameter_value" varchar(100) NOT NULL,
  "ml_feature_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_timeseries_feature_value" (
  "timeseries_data_id" bigint NOT NULL,
  "ml_feature_id" int NOT NULL,
  "feature_value" float NOT NULL,
  "primary" key(timeseries_data_id,ml_feature_id)
);

CREATE TABLE "ml_dataset_version_timeseries_data" (
  "ml_dataset_version_id" int NOT NULL,
  "timeseries_data_id" bigint NOT NULL,
  "primary" key(ml_dataset_version_id,timeseries_data_id)
);

CREATE TABLE "ml_dataset_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_name" varchar(100) UNIQUE NOT NULL,
  "start_date" date,
  "end_date" date,
  "candle_count" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "ml_dataset_version_filter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filter" varchar(50) NOT NULL,
  "operator" varchar(10) NOT NULL,
  "filter_value" varchar(255) NOT NULL,
  "description" text,
  "ml_dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_optimization_variant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "max_depth" int,
  "learning_rate" float,
  "n_estimators" int,
  "subsample" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "wfe_50plus_db" int,
  "atlag_wfe_pct" float,
  "atlag_sharpe" float,
  "max_sharpe" float,
  "is_best_for_version" bool DEFAULT false,
  "ml_model_id" int NOT NULL,
  "ml_dataset_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_optimization_trade" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "entry_time" timestamp NOT NULL,
  "entry_price" float NOT NULL,
  "exit_time" timestamp NOT NULL,
  "exit_price" float NOT NULL,
  "pnl_raw" float NOT NULL,
  "pnl_log_return" float NOT NULL,
  "ml_optimization_variant_id" int NOT NULL,
  "wfo_fold_index" int NOT NULL DEFAULT 1,
  "created_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_test_statistical_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_statistical_metrics_name" varchar(100) NOT NULL,
  "test_statistical_value" float NOT NULL,
  "ml_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_live_trading_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "live_trading_metrics_name" varchar(100) NOT NULL,
  "live_trading_value" float NOT NULL,
  "ml_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_strategy" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "model_architecture" varchar(100) NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_strategy_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_name" varchar(100) NOT NULL,
  "description" text,
  "has_ltf" bool DEFAULT false,
  "ltf_ratio" decimal,
  "ltf_use_same_analysis" bool DEFAULT true,
  "has_htf" bool DEFAULT false,
  "htf_ratio" decimal,
  "htf_use_same_analysis" bool DEFAULT true,
  "pers_strategy_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_analysis_part" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_analysis_tool" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "value" varchar(20),
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_analysis_sub_tool" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "value" varchar(20),
  "description" text,
  "pers_analysis_tool_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_analysis_version_part_tool" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pers_strategy_version_id" int NOT NULL,
  "pers_analysis_part_id" int NOT NULL,
  "pers_analysis_tool_id" int NOT NULL,
  "pers_analysis_sub_tool_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_analysis_mtf_custom" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mtf_type" enum(ltf,htf) NOT NULL,
  "description" text,
  "pers_analysis_version_part_tool_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_risk_management" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "risk_per_trade" float NOT NULL,
  "risk_model_type" varchar(30) NOT NULL DEFAULT 'fixed_pct',
  "min_rr" float,
  "max_rr" float,
  "min_distance_to_sl_tick" int,
  "max_daily_drawdown_pct" float,
  "max_drawdown_pct" float,
  "max_open_positions" int DEFAULT 1,
  "max_trades_per_day" int,
  "max_position_size_pct" float,
  "allow_overnight" bool DEFAULT false,
  "max_holding_time_minutes" int,
  "description" text,
  "pers_strategy_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_optimization_run" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "pers_strategy_version_id" int NOT NULL,
  "ml_dataset_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_optimization_variant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_best_for_run" bool DEFAULT false,
  "pers_optimization_run_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_optimization_variant_tool_override" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "overridden_value" varchar(20) NOT NULL,
  "pers_analysis_tool_id" int NOT NULL,
  "pers_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_optimization_variant_sub_tool_override" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "overridden_value" varchar(20) NOT NULL,
  "pers_analysis_sub_tool_id" int NOT NULL,
  "pers_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_optimization_variant_risk_override" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "risk_parameter_name" varchar(50) NOT NULL,
  "overridden_value" varchar(50) NOT NULL,
  "pers_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_optimization_trade" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "entry_time" timestamp NOT NULL,
  "entry_price" float NOT NULL,
  "exit_time" timestamp NOT NULL,
  "exit_price" float NOT NULL,
  "pnl_r" float NOT NULL,
  "distance_to_sl_tick" int NOT NULL,
  "max_runup" float,
  "max_drawdown" float,
  "pers_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_live_trading_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "live_trading_metrics_name" varchar(100) NOT NULL,
  "live_trading_value" float NOT NULL,
  "pers_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "pers_test_statistical_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metric_name" varchar(100) NOT NULL,
  "metric_value" float NOT NULL,
  "pers_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_signal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "signal_type" "enum(BUY_LONG,SELL_SHORT,EXIT_LONG,EXIT_SHORT)" NOT NULL,
  "confidence" float NOT NULL,
  "ml_suggested_entry_price" float NOT NULL,
  "ml_suggested_stop_loss" float,
  "ml_suggested_take_profit" float,
  "position_size" float NOT NULL,
  "signal_time" timestamp DEFAULT (now()),
  "ml_model_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

COMMENT ON COLUMN "timeseries_data"."time" IS 'The time of the candle (e.g. 2018-01-02T00:00:00+01:00)';

COMMENT ON COLUMN "timeseries_data"."log_return" IS 'e.g.: 0.01 = +1%';

COMMENT ON COLUMN "ml_hyperparameter"."n_estimators" IS 'The number of decision trees in the model';

COMMENT ON COLUMN "ml_hyperparameter"."max_depth" IS 'The maximum depth of the trees';

COMMENT ON COLUMN "ml_hyperparameter"."min_samples_split" IS 'The minimum number of samples required to split an internal node';

COMMENT ON COLUMN "ml_hyperparameter"."subsample" IS 'Subsample ratio of the training instances (0.0 - 1.0)';

COMMENT ON COLUMN "ml_hyperparameter"."learning_rate" IS 'Learning rate / step size (e.g. 0.01, 0.1)';

COMMENT ON COLUMN "ml_hyperparameter"."colsample_bytree" IS 'Subsample ratio of columns when constructing each tree (0.0 - 1.0)';

COMMENT ON COLUMN "ml_hyperparameter"."reg_alpha" IS 'L1 regularization term on weights (XGBoost Alpha)';

COMMENT ON COLUMN "ml_hyperparameter"."reg_lambda" IS 'L2 regularization term on weights (XGBoost Lambda)';

COMMENT ON COLUMN "ml_hyperparameter"."optimizer" IS 'Name of the optimizer algorithm (e.g. adam, sgd)';

COMMENT ON COLUMN "ml_hyperparameter"."batch_size" IS 'Batch size during training';

COMMENT ON COLUMN "ml_hyperparameter"."epochs" IS 'Number of training iterations';

COMMENT ON COLUMN "ml_hyperparameter"."random_state" IS 'Seed number responsible for reproducibility (Must always be the same number)';

COMMENT ON COLUMN "ml_model"."model_architecture" IS 'Model type/algorithm (e.g. XGBoost)';

COMMENT ON COLUMN "ml_model"."target" IS 'The target variable that the model predicts - long/short';

COMMENT ON COLUMN "ml_model_version"."model_version" IS 'Model version number (e.g. v2.4.1)';

COMMENT ON COLUMN "ml_model_version"."environment_state" IS 'The current lifecycle state of the model (e.g. Production, Testing)';

COMMENT ON COLUMN "ml_feature"."source_data" IS 'Where it originates from e.g. OHLCV, OrderBook, Sentiment';

COMMENT ON COLUMN "ml_feature"."time_lag_steps" IS 'How many steps it is shifted by (e.g. 1 hour before this)';

COMMENT ON COLUMN "ml_feature_parameter"."parameter_name" IS 'e.g. indicator';

COMMENT ON COLUMN "ml_feature_parameter"."parameter_value" IS 'The values of the indicator';

COMMENT ON COLUMN "ml_timeseries_feature_value"."feature_value" IS 'The actual calculated numerical value in the given hour';

COMMENT ON COLUMN "ml_dataset_version"."version_name" IS 'E.g. v1.0.0';

COMMENT ON COLUMN "ml_dataset_version"."start_date" IS 'The very first exchange day in the database';

COMMENT ON COLUMN "ml_dataset_version"."end_date" IS 'The very last exchange day in the database';

COMMENT ON COLUMN "ml_dataset_version_filter"."filter" IS 'e.g. volume, close_price, asset_type';

COMMENT ON COLUMN "ml_dataset_version_filter"."operator" IS 'e.g. >, <, =, IN, BETWEEN';

COMMENT ON COLUMN "ml_dataset_version_filter"."filter_value" IS 'e.g. 100000, US';

COMMENT ON COLUMN "ml_optimization_variant"."wfe_50plus_db" IS 'WFE_50plus_db';

COMMENT ON COLUMN "ml_optimization_variant"."atlag_wfe_pct" IS 'Average_WFE_%';

COMMENT ON COLUMN "ml_optimization_variant"."atlag_sharpe" IS 'Average_Sharpe';

COMMENT ON COLUMN "ml_optimization_variant"."max_sharpe" IS 'Max_Sharpe';

COMMENT ON COLUMN "ml_optimization_variant"."is_best_for_version" IS 'false = not the best, true = best optimazation for the version';

COMMENT ON COLUMN "ml_optimization_trade"."entry_time" IS 'The execution time when the position was opened';

COMMENT ON COLUMN "ml_optimization_trade"."entry_price" IS 'The execution entry price';

COMMENT ON COLUMN "ml_optimization_trade"."exit_time" IS 'The execution time when the position was closed';

COMMENT ON COLUMN "ml_optimization_trade"."exit_price" IS 'The execution exit price';

COMMENT ON COLUMN "ml_optimization_trade"."pnl_raw" IS 'Net profit or loss in points or absolute currency value';

COMMENT ON COLUMN "ml_optimization_trade"."pnl_log_return" IS 'The return of the trade formatted as log return';

COMMENT ON COLUMN "pers_strategy"."model_architecture" IS 'bot, manual, hibrid, manual+execution prog.';

COMMENT ON COLUMN "pers_strategy_version"."version_name" IS 'v1.0.0';

COMMENT ON COLUMN "pers_strategy_version"."has_ltf" IS 'false = startegy has no lower tf, true = strategy has lower tf';

COMMENT ON COLUMN "pers_strategy_version"."ltf_ratio" IS 'how much lower it is than the main tf';

COMMENT ON COLUMN "pers_strategy_version"."ltf_use_same_analysis" IS 'the analysis is same as the main tf';

COMMENT ON COLUMN "pers_strategy_version"."has_htf" IS 'false = startegy has no bigger tf, true = strategy has bigger tf';

COMMENT ON COLUMN "pers_strategy_version"."htf_ratio" IS 'how much bigger it is than the main tf';

COMMENT ON COLUMN "pers_strategy_version"."htf_use_same_analysis" IS 'the analysis is same as the main tf';

COMMENT ON COLUMN "pers_analysis_part"."name" IS 'Trend determination, Theory, Trend lvl, Speed measurement, momentum, signal, TP, SL';

COMMENT ON COLUMN "pers_analysis_tool"."name" IS 'RSI_14';

COMMENT ON COLUMN "pers_analysis_sub_tool"."name" IS 'sma_9, RSI_controll_zone';

COMMENT ON COLUMN "pers_risk_management"."risk_per_trade" IS '%, amount';

COMMENT ON COLUMN "pers_optimization_variant"."is_best_for_run" IS 'false = not the best, true = best optimazation for the version';

COMMENT ON COLUMN "pers_optimization_variant_tool_override"."overridden_value" IS 'e.g. 10 instead of 14';

COMMENT ON COLUMN "pers_optimization_variant_sub_tool_override"."overridden_value" IS 'e.g. 14 instead of 9';

COMMENT ON COLUMN "pers_optimization_variant_risk_override"."risk_parameter_name" IS 'e.g. min_rr';

COMMENT ON COLUMN "pers_optimization_trade"."pnl_r" IS 'pnl in unit';

COMMENT ON COLUMN "pers_optimization_trade"."max_runup" IS 'MFE - Maximum Favorable Excursion';

COMMENT ON COLUMN "pers_optimization_trade"."max_drawdown" IS 'MAE - Maximum Adverse Excursion';

COMMENT ON COLUMN "pers_live_trading_metric"."live_trading_metrics_name" IS 'Pl. Live_Sharpe, Live_Win_Rate, Current_Drawdown';

COMMENT ON COLUMN "pers_test_statistical_metric"."metric_name" IS 'Sharpe, Drawdown_Pct, Win_Rate, Total_Return_Pct';

COMMENT ON COLUMN "ml_signal"."ticker" IS 'e.g. NQ, BTCUSDT';

COMMENT ON COLUMN "ml_signal"."confidence" IS 'probability of long/short';

COMMENT ON COLUMN "ml_signal"."ml_suggested_entry_price" IS 'The entry price suggested by the ML';

COMMENT ON COLUMN "ml_signal"."ml_suggested_stop_loss" IS 'The initial Stop Loss calculated by the ML';

COMMENT ON COLUMN "ml_signal"."ml_suggested_take_profit" IS 'The initial Take Profit calculated by the ML';

COMMENT ON COLUMN "ml_signal"."position_size" IS 'The size suggested by the ML (capital % or pieces)';

COMMENT ON COLUMN "ml_signal"."signal_time" IS 'The moment the signal was generated';

ALTER TABLE "ml_dataset_version" ADD FOREIGN KEY ("id") REFERENCES "ml_dataset_version_timeseries_data" ("ml_dataset_version_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "timeseries_data" ADD FOREIGN KEY ("id") REFERENCES "ml_dataset_version_timeseries_data" ("timeseries_data_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "timeseries_data" ADD FOREIGN KEY ("id") REFERENCES "ml_timeseries_feature_value" ("timeseries_data_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_feature" ADD FOREIGN KEY ("id") REFERENCES "ml_timeseries_feature_value" ("ml_feature_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_dataset_version" ADD FOREIGN KEY ("id") REFERENCES "ml_dataset_version_filter" ("ml_dataset_version_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model" ADD FOREIGN KEY ("id") REFERENCES "ml_model_version" ("ml_model_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_hyperparameter" ADD FOREIGN KEY ("id") REFERENCES "ml_model_version" ("ml_hyperparameter_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_dataset_version" ADD FOREIGN KEY ("id") REFERENCES "ml_model_version" ("ml_dataset_version_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("id") REFERENCES "ml_model_version_feature" ("ml_model_version_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_feature" ADD FOREIGN KEY ("id") REFERENCES "ml_model_version_feature" ("ml_feature_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_feature" ADD FOREIGN KEY ("id") REFERENCES "ml_feature_parameter" ("ml_feature_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("id") REFERENCES "ml_signal" ("ml_model_version_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "ml_test_statistical_metric" ("ml_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "ml_live_trading_metric" ("ml_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_dataset_version" ADD FOREIGN KEY ("id") REFERENCES "ml_optimization_variant" ("ml_dataset_version_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "ml_optimization_trade" ("ml_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model" ADD FOREIGN KEY ("id") REFERENCES "ml_optimization_variant" ("ml_model_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_strategy" ADD FOREIGN KEY ("id") REFERENCES "pers_strategy_version" ("pers_strategy_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_tool" ADD FOREIGN KEY ("id") REFERENCES "pers_analysis_sub_tool" ("pers_analysis_tool_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_strategy_version" ADD FOREIGN KEY ("id") REFERENCES "pers_analysis_version_part_tool" ("pers_strategy_version_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_part" ADD FOREIGN KEY ("id") REFERENCES "pers_analysis_version_part_tool" ("pers_analysis_part_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_tool" ADD FOREIGN KEY ("id") REFERENCES "pers_analysis_version_part_tool" ("pers_analysis_tool_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_sub_tool" ADD FOREIGN KEY ("id") REFERENCES "pers_analysis_version_part_tool" ("pers_analysis_sub_tool_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_version_part_tool" ADD FOREIGN KEY ("id") REFERENCES "pers_analysis_mtf_custom" ("pers_analysis_version_part_tool_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_strategy_version" ADD FOREIGN KEY ("id") REFERENCES "pers_risk_management" ("pers_strategy_version_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_strategy_version" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_run" ("pers_strategy_version_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_dataset_version" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_run" ("ml_dataset_version_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_run" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_variant" ("pers_optimization_run_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_variant_tool_override" ("pers_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_tool" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_variant_tool_override" ("pers_analysis_tool_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_variant_sub_tool_override" ("pers_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_analysis_sub_tool" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_variant_sub_tool_override" ("pers_analysis_sub_tool_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_variant_risk_override" ("pers_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "pers_optimization_trade" ("pers_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "pers_test_statistical_metric" ("pers_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pers_optimization_variant" ADD FOREIGN KEY ("id") REFERENCES "pers_live_trading_metric" ("pers_optimization_variant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
