CREATE TABLE "timeseries_data" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "time" timestamp NOT NULL,
  "open" float NOT NULL,
  "high" float NOT NULL,
  "low" float NOT NULL,
  "close" float NOT NULL,
  "log_return" float NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_hyperparameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hyperparameter_set_name" varchar(100),
  "n_estimators" int,
  "max_depth" int,
  "min_samples_split" int,
  "subsample" float,
  "learning_rate" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "optimizer" varchar(50),
  "batch_size" int,
  "epochs" int,
  "random_state" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_name" varchar(100) UNIQUE NOT NULL,
  "model_architecture" varchar(100),
  "target" varchar(15),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_version" varchar(100),
  "environment_state" "enum(Development,Learning,Demo,Production,Relearning)",
  "ml_model_id" int,
  "ml_hyperparameter_id" int,
  "ml_dataset_version_id" int,
  "ml_optimization_variant_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_model_version_feature" (
  "ml_model_version_id" int,
  "ml_feature_id" int,
  "primary" key(ml_model_version_id,ml_feature_id)
);

CREATE TABLE "ml_feature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar(100) NOT NULL,
  "feature_description" text,
  "source_data" varchar(100) NOT NULL,
  "time_lag_steps" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_feature_parameter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parameter_name" varchar(100) NOT NULL,
  "parameter_value" varchar(100) NOT NULL,
  "ml_feature_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_timeseries_feature_value" (
  "timeseries_data_id" bigint NOT NULL,
  "ml_feature_id" int NOT NULL,
  "feature_value" float NOT NULL,
  "primary" key(timeseries_data_id,ml_feature_id)
);

CREATE TABLE "ml_dataset_version_timeseries_data" (
  "ml_dataset_version_id" int NOT NULL,
  "timeseries_data_id" bigint NOT NULL,
  "primary" key(ml_dataset_version_id,timeseries_data_id)
);

CREATE TABLE "ml_dataset_version" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_name" varchar(100) UNIQUE NOT NULL,
  "start_date" date,
  "end_date" date,
  "candle_count" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_dataset_version_filter" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filter" varchar(50) NOT NULL,
  "operator" varchar(10) NOT NULL,
  "filter_value" varchar(255) NOT NULL,
  "description" text,
  "ml_dataset_version_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_optimization_variant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "max_depth" int,
  "learning_rate" float,
  "n_estimators" int,
  "subsample" float,
  "colsample_bytree" float,
  "reg_alpha" float,
  "reg_lambda" float,
  "wfe_50plus_db" int,
  "atlag_wfe_pct" float,
  "atlag_sharpe" float,
  "max_sharpe" float,
  "is_best_for_version" bool DEFAULT false,
  "ml_model_id" int NOT NULL,
  "ml_dataset_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "ml_optimization_trade" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "entry_time" timestamp NOT NULL,
  "entry_price" float NOT NULL,
  "exit_time" timestamp NOT NULL,
  "exit_price" float NOT NULL,
  "pnl_raw" float NOT NULL,
  "pnl_log_return" float NOT NULL,
  "ml_optimization_variant_id" int NOT NULL,
  "wfo_fold_index" int NOT NULL DEFAULT 1,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "ml_test_statistical_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "test_statistical_metrics_name" varchar(100) NOT NULL,
  "test_statistical_value" float NOT NULL,
  "ml_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "ml_live_trading_metric" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "live_trading_metrics_name" varchar(100) NOT NULL,
  "live_trading_value" float NOT NULL,
  "ml_optimization_variant_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "strategy" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "strategy_version" (
  "id" int PRIMARY KEY,
  "name" varchar(20),
  "description" text,
  "strategy_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "is_deleted" bool DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ml_signal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticker" varchar(20) NOT NULL,
  "direction" "enum(LONG,SHORT)" NOT NULL,
  "signal_type" "enum(BUY_LONG,SELL_SHORT,EXIT_LONG,EXIT_SHORT)" NOT NULL,
  "confidence" float NOT NULL,
  "ml_suggested_entry_price" float NOT NULL,
  "ml_suggested_stop_loss" float,
  "ml_suggested_take_profit" float,
  "position_size" float NOT NULL,
  "signal_time" timestamp DEFAULT (now()),
  "ml_model_version_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "timeseries_data"."time" IS 'The time of the candle (e.g. 2018-01-02T00:00:00+01:00)';

COMMENT ON COLUMN "timeseries_data"."log_return" IS 'e.g.: 0.01 = +1%';

COMMENT ON COLUMN "ml_hyperparameter"."n_estimators" IS 'The number of decision trees in the model';

COMMENT ON COLUMN "ml_hyperparameter"."max_depth" IS 'The maximum depth of the trees';

COMMENT ON COLUMN "ml_hyperparameter"."min_samples_split" IS 'The minimum number of samples required to split an internal node';

COMMENT ON COLUMN "ml_hyperparameter"."subsample" IS 'Subsample ratio of the training instances (0.0 - 1.0)';

COMMENT ON COLUMN "ml_hyperparameter"."learning_rate" IS 'Learning rate / step size (e.g. 0.01, 0.1)';

COMMENT ON COLUMN "ml_hyperparameter"."colsample_bytree" IS 'Subsample ratio of columns when constructing each tree (0.0 - 1.0)';

COMMENT ON COLUMN "ml_hyperparameter"."reg_alpha" IS 'L1 regularization term on weights (XGBoost Alpha)';

COMMENT ON COLUMN "ml_hyperparameter"."reg_lambda" IS 'L2 regularization term on weights (XGBoost Lambda)';

COMMENT ON COLUMN "ml_hyperparameter"."optimizer" IS 'Name of the optimizer algorithm (e.g. adam, sgd)';

COMMENT ON COLUMN "ml_hyperparameter"."batch_size" IS 'Batch size during training';

COMMENT ON COLUMN "ml_hyperparameter"."epochs" IS 'Number of training iterations';

COMMENT ON COLUMN "ml_hyperparameter"."random_state" IS 'Seed number responsible for reproducibility (Must always be the same number)';

COMMENT ON COLUMN "ml_model"."model_architecture" IS 'Model type/algorithm (e.g. XGBoost)';

COMMENT ON COLUMN "ml_model"."target" IS 'The target variable that the model predicts - long/short';

COMMENT ON COLUMN "ml_model_version"."model_version" IS 'Model version number (e.g. v2.4.1)';

COMMENT ON COLUMN "ml_model_version"."environment_state" IS 'The current lifecycle state of the model (e.g. Production, Testing)';

COMMENT ON COLUMN "ml_feature"."source_data" IS 'Where it originates from e.g. OHLCV, OrderBook, Sentiment';

COMMENT ON COLUMN "ml_feature"."time_lag_steps" IS 'How many steps it is shifted by (e.g. 1 hour before this)';

COMMENT ON COLUMN "ml_feature_parameter"."parameter_name" IS 'e.g. indicator';

COMMENT ON COLUMN "ml_feature_parameter"."parameter_value" IS 'The values of the indicator';

COMMENT ON COLUMN "ml_timeseries_feature_value"."feature_value" IS 'The actual calculated numerical value in the given hour';

COMMENT ON COLUMN "ml_dataset_version"."version_name" IS 'E.g. v1.0.0';

COMMENT ON COLUMN "ml_dataset_version"."start_date" IS 'The very first exchange day in the database';

COMMENT ON COLUMN "ml_dataset_version"."end_date" IS 'The very last exchange day in the database';

COMMENT ON COLUMN "ml_dataset_version_filter"."filter" IS 'e.g. volume, close_price, asset_type';

COMMENT ON COLUMN "ml_dataset_version_filter"."operator" IS 'e.g. >, <, =, IN, BETWEEN';

COMMENT ON COLUMN "ml_dataset_version_filter"."filter_value" IS 'e.g. 100000, US';

COMMENT ON COLUMN "ml_optimization_variant"."wfe_50plus_db" IS 'WFE_50plus_db';

COMMENT ON COLUMN "ml_optimization_variant"."atlag_wfe_pct" IS 'Average_WFE_%';

COMMENT ON COLUMN "ml_optimization_variant"."atlag_sharpe" IS 'Average_Sharpe';

COMMENT ON COLUMN "ml_optimization_variant"."max_sharpe" IS 'Max_Sharpe';

COMMENT ON COLUMN "ml_optimization_variant"."is_best_for_version" IS 'false = not the best, true = best optimazation for the version';

COMMENT ON COLUMN "ml_optimization_trade"."entry_time" IS 'The execution time when the position was opened';

COMMENT ON COLUMN "ml_optimization_trade"."entry_price" IS 'The execution entry price';

COMMENT ON COLUMN "ml_optimization_trade"."exit_time" IS 'The execution time when the position was closed';

COMMENT ON COLUMN "ml_optimization_trade"."exit_price" IS 'The execution exit price';

COMMENT ON COLUMN "ml_optimization_trade"."pnl_raw" IS 'Net profit or loss in points or absolute currency value';

COMMENT ON COLUMN "ml_optimization_trade"."pnl_log_return" IS 'The return of the trade formatted as log return';

COMMENT ON COLUMN "ml_signal"."ticker" IS 'e.g. NQ, BTCUSDT';

COMMENT ON COLUMN "ml_signal"."confidence" IS 'probability of long/short';

COMMENT ON COLUMN "ml_signal"."ml_suggested_entry_price" IS 'The entry price suggested by the ML';

COMMENT ON COLUMN "ml_signal"."ml_suggested_stop_loss" IS 'The initial Stop Loss calculated by the ML';

COMMENT ON COLUMN "ml_signal"."ml_suggested_take_profit" IS 'The initial Take Profit calculated by the ML';

COMMENT ON COLUMN "ml_signal"."position_size" IS 'The size suggested by the ML (capital % or pieces)';

COMMENT ON COLUMN "ml_signal"."signal_time" IS 'The moment the signal was generated';

ALTER TABLE "ml_dataset_version_timeseries" ADD FOREIGN KEY ("ml_dataset_version_id") REFERENCES "ml_dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_dataset_version_timeseries" ADD FOREIGN KEY ("timeseries_data_id") REFERENCES "timeseries_data" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_timeseries_feature_value" ADD FOREIGN KEY ("timeseries_data_id") REFERENCES "timeseries_data" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_timeseries_feature_value" ADD FOREIGN KEY ("ml_feature_id") REFERENCES "ml_feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_dataset_version_filter" ADD FOREIGN KEY ("ml_dataset_version_id") REFERENCES "ml_dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("ml_model_id") REFERENCES "ml_model" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("ml_hyperparameter_id") REFERENCES "ml_hyperparameter" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("ml_dataset_version_id") REFERENCES "ml_dataset_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version_feature" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version_feature" ADD FOREIGN KEY ("ml_feature_id") REFERENCES "ml_feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_signal" ADD FOREIGN KEY ("ml_model_version_id") REFERENCES "ml_model_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_feature_parameter" ADD FOREIGN KEY ("ml_feature_id") REFERENCES "ml_feature" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_test_statistical_metric" ADD FOREIGN KEY ("ml_optimization_variant_id") REFERENCES "ml_optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_live_trading_metric" ADD FOREIGN KEY ("ml_optimization_variant_id") REFERENCES "ml_optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_optimization_trade" ADD FOREIGN KEY ("ml_optimization_variant_id") REFERENCES "ml_optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_model_version" ADD FOREIGN KEY ("ml_optimization_variant_id") REFERENCES "ml_optimization_variant" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ml_optimization_variant" ADD FOREIGN KEY ("ml_model_id") REFERENCES "ml_model" ("id") DEFERRABLE INITIALLY IMMEDIATE;
